apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: off-campus-housing-tracker
  labels:
    app: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - name: http
      port: 4015
      targetPort: 4015
    - name: grpc
      port: 50065
      targetPort: 50065
