/* eslint-disable — generated by scripts/testing/generate-route-smoke-tests.mjs */
import { vitestRouteHitAgent } from "../vitest-route-hit-agent.js";
import { describe, it, expect, beforeAll } from "vitest";

describe("AUTO OpenAPI route smoke (api-gateway)", () => {
  let app: import("express").Express;
  let agent: ReturnType<typeof vitestRouteHitAgent>;
  beforeAll(async () => {
    const mod = await import("../../src/server.js");
    app = mod.app;
    agent = vitestRouteHitAgent(app);
  });

  it("AUTO GET /healthz", async () => {
    const res = await agent.get(`/healthz`);
    expect(res.status).toBeGreaterThanOrEqual(200);
    expect(res.status).toBeLessThan(600);
  });

  it("AUTO GET /api/healthz", async () => {
    const res = await agent.get(`/api/healthz`);
    expect(res.status).toBeGreaterThanOrEqual(200);
    expect(res.status).toBeLessThan(600);
  });

  it("AUTO GET /health", async () => {
    const res = await agent.get(`/health`);
    expect(res.status).toBeGreaterThanOrEqual(200);
    expect(res.status).toBeLessThan(600);
  });

  it("AUTO GET /api/health", async () => {
    const res = await agent.get(`/api/health`);
    expect(res.status).toBeGreaterThanOrEqual(200);
    expect(res.status).toBeLessThan(600);
  });

  it("AUTO GET /readyz", async () => {
    const res = await agent.get(`/readyz`);
    expect(res.status).toBeGreaterThanOrEqual(200);
    expect(res.status).toBeLessThan(600);
  });

  it("AUTO GET /api/readyz", async () => {
    const res = await agent.get(`/api/readyz`);
    expect(res.status).toBeGreaterThanOrEqual(200);
    expect(res.status).toBeLessThan(600);
  });

  it("AUTO GET /metrics", async () => {
    const res = await agent.get(`/metrics`);
    expect(res.status).toBeGreaterThanOrEqual(200);
    expect(res.status).toBeLessThan(600);
  });

  it("AUTO GET /whoami", async () => {
    const res = await agent.get(`/whoami`);
    expect(res.status).toBeGreaterThanOrEqual(200);
    expect(res.status).toBeLessThan(600);
  });

  it("AUTO GET /api/debug/full-trace", async () => {
    const res = await agent.get(`/api/debug/full-trace`);
    expect(res.status).toBeGreaterThanOrEqual(200);
    expect(res.status).toBeLessThan(600);
  });

  it("AUTO GET /api/debug/headers", async () => {
    const res = await agent.get(`/api/debug/headers`);
    expect(res.status).toBeGreaterThanOrEqual(200);
    expect(res.status).toBeLessThan(600);
  });

});
