apiVersion: v1
kind: Service
metadata:
  name: kafka-ca-exporter
  namespace: off-campus-housing-tracker
  labels:
    app: kafka-ca-exporter
spec:
  selector:
    app: kafka-ca-exporter
  ports:
    - name: metrics
      port: 9105
      targetPort: metrics
