# BGPAdvertisement: advertise off-campus-housing-tracker-pool via BGP. Apply after BGPPeer.
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: off-campus-housing-tracker-pool
  namespace: metallb-system
spec:
  ipAddressPools:
  - off-campus-housing-tracker-pool
