import "./bootstrap-tls.mjs";
import { getBearerToken, qaAuthWarmup, qaBaseUrl } from "./auth-client.mjs";

const LISTING_CACHE_PATH = process.env.ANALYTICS_QA_LISTING_CACHE_PATH?.trim() || "bench_logs/qa-listing.json";

async function readJsonFile(path) {
  try {
    const { readFile } = await import("node:fs/promises");
    return JSON.parse(await readFile(path, "utf8"));
  } catch {
    return null;
  }
}

async function writeJsonFile(path, obj) {
  try {
    const { mkdir, writeFile } = await import("node:fs/promises");
    const { dirname } = await import("node:path");
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, `${JSON.stringify(obj)}\n`, "utf8");
  } catch {
    /* best effort cache */
  }
}

function withBearer(token, base = {}) {
  return { ...base, Authorization: `Bearer ${token}` };
}

export async function ensureGatewayReachable(baseUrl = qaBaseUrl()) {
  const checks = [
    { path: "/api/readyz", label: "gateway readyz" },
    { path: "/api/analytics/healthz", label: "analytics healthz" },
  ];
  for (const c of checks) {
    const res = await fetch(`${baseUrl}${c.path}`).catch(() => null);
    if (!res || !res.ok) {
      const code = res ? res.status : "unreachable";
      throw new Error(
        `[qa-bootstrap] ${c.label} failed (${code}). Gateway build does not match expected OPEN_ROUTES revision or upstream is unhealthy.`,
      );
    }
  }
}

export async function ensureAnalyzeRoutePresent(baseUrl, token) {
  const probeId = "00000000-0000-4000-8000-000000000001";
  const paths = [
    `/api/analytics/insights/listing/${probeId}/analyze`,
    `/api/analytics/listing/${probeId}/analyze`,
  ];
  for (const p of paths) {
    const res = await fetch(`${baseUrl}${p}`, {
      method: "POST",
      headers: withBearer(token, { "Content-Type": "application/json" }),
      body: JSON.stringify({ audience: "renter", analysis_depth: "quick" }),
    }).catch(() => null);
    if (!res) continue;
    const txt = await res.text().catch(() => "");
    if (res.ok) return;
    const ct = String(res.headers.get("content-type") || "");
    const isExpressCannotPost = /Cannot POST/i.test(txt);
    // Route exists if we get JSON semantics (even with 4xx/5xx), not raw "Cannot POST".
    if (!isExpressCannotPost && ct.includes("application/json")) return;
  }
  throw new Error(
    "[qa-bootstrap] analytics analyze route unavailable on deployed stack (Cannot POST). Redeploy analytics-service/api-gateway revision with listing-analyze endpoint.",
  );
}

async function getListing(baseUrl, listingId, token) {
  const urls = [`${baseUrl}/api/listings/${listingId}`, `${baseUrl}/api/listings/listings/${listingId}`];
  let res = null;
  for (const url of urls) {
    res = await fetch(url);
    if (res.status === 401) {
      res = await fetch(url, { headers: withBearer(token) });
    }
    if (res.ok || res.status !== 404) return res;
  }
  return res;
}

function todayISO() {
  const d = new Date();
  const y = d.getUTCFullYear();
  const m = String(d.getUTCMonth() + 1).padStart(2, "0");
  const day = String(d.getUTCDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

async function createListing(baseUrl, token) {
  const payload = {
    title: "QA Test Listing",
    description:
      "Autogenerated listing for analytics QA. Near campus, utilities split, in-unit laundry, no broker fee.",
    price_cents: 120000,
    effective_from: todayISO(),
    amenities: ["wifi", "laundry"],
    smoke_free: true,
    pet_friendly: false,
    furnished: false,
  };
  const res = await fetch(`${baseUrl}/api/listings/create`, {
    method: "POST",
    headers: withBearer(token, { "Content-Type": "application/json" }),
    body: JSON.stringify(payload),
  });
  const txt = await res.text().catch(() => "");
  let body = {};
  try {
    body = txt ? JSON.parse(txt) : {};
  } catch {
    body = { raw: txt };
  }
  if (!res.ok) {
    throw new Error(`[qa-bootstrap] listing create failed ${res.status} ${txt.slice(0, 400)}`);
  }
  const id = String(body.id ?? body.listing_id ?? "").trim();
  if (!id) throw new Error("[qa-bootstrap] listing create succeeded but no id returned");
  return id;
}

export async function ensureListingExists(baseUrl, token) {
  const configured = process.env.LISTING_ID?.trim();
  const cached = process.env.ANALYTICS_QA_LISTING_CACHE === "0" ? null : await readJsonFile(LISTING_CACHE_PATH);
  const candidates = [configured, cached?.listing_id].filter(Boolean);

  for (const id of candidates) {
    const res = await getListing(baseUrl, id, token);
    if (res.ok) return id;
    if (res.status !== 404) {
      const body = await res.text().catch(() => "");
      throw new Error(`[qa-bootstrap] listing probe failed ${res.status} for ${id}: ${body.slice(0, 400)}`);
    }
  }

  if (process.env.ANALYTICS_QA_AUTO_CREATE_LISTING === "0") {
    throw new Error("[qa-bootstrap] listing missing and ANALYTICS_QA_AUTO_CREATE_LISTING=0");
  }
  const created = await createListing(baseUrl, token);
  await writeJsonFile(LISTING_CACHE_PATH, { listing_id: created, created_at: Date.now() });
  return created;
}

export async function bootstrapQaContext() {
  const baseUrl = qaBaseUrl();
  await qaAuthWarmup();
  await ensureGatewayReachable(baseUrl);
  const token = await getBearerToken();
  await ensureAnalyzeRoutePresent(baseUrl, token);
  const listingId = await ensureListingExists(baseUrl, token);
  return { baseUrl, token, listingId };
}
