apiVersion: v1
kind: Service
metadata:
  name: messaging-service
  namespace: off-campus-housing-tracker
  labels: { app: messaging-service }
spec:
  selector: { app: messaging-service }
  ports:
    - name: http
      port: 4014
      targetPort: 4014
    - name: grpc
      port: 50064
      targetPort: 50064
