apiVersion: apps/v1
kind: Deployment
metadata:
  name: records-service
  namespace: off-campus-housing-tracker
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: listings-service
  namespace: off-campus-housing-tracker
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: off-campus-housing-tracker
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-ai-service
  namespace: off-campus-housing-tracker
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-service
  namespace: off-campus-housing-tracker
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-service
  namespace: off-campus-housing-tracker
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-monitor
  namespace: off-campus-housing-tracker
spec:
  replicas: 1

