apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-service
  namespace: off-campus-housing-tracker
spec:
  template:
    spec:
      containers:
        - name: app
          image: off-campus-housing-tracker-shopping-service:latest

