apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-service
  namespace: off-campus-housing-tracker
spec:
  template:
    spec:
      containers:
      - name: app
        imagePullPolicy: Never

