apiVersion: v1
kind: Namespace
metadata:
  name: off-campus-housing-tracker
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx