apiVersion: v1
kind: Service
metadata:
  name: trust-service
  namespace: off-campus-housing-tracker
  labels:
    app: trust-service
spec:
  selector:
    app: trust-service
  ports:
    - name: http
      port: 4016
      targetPort: 4016
    - name: grpc
      port: 50066
      targetPort: 50066
