#!/usr/bin/env bash
# Emit cert-manager Certificate resources (one per broker) with deterministic dnsNames.
# Requires cert-manager CRDs installed; apply ClusterIssuer first, then this kustomization.
#
# Usage (repo root):
#   ./scripts/gen-kafka-cert-crds.sh
#   NAMESPACE=my-ns REPLICAS=5 ./scripts/gen-kafka-cert-crds.sh
#
# Output: infra/k8s/kafka-certs/certificates/kafka-<n>-cert.yaml
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
NS="${NAMESPACE:-off-campus-housing-tracker}"
REPLICAS="${REPLICAS:-3}"
OUT="${REPO_ROOT}/infra/k8s/kafka-certs/certificates"

mkdir -p "$OUT"

for ((i = 0; i < REPLICAS; i++)); do
  f="${OUT}/kafka-${i}-cert.yaml"
  cat >"$f" <<EOF
# Generated by scripts/gen-kafka-cert-crds.sh (do not hand-edit SANs — re-run script).
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-${i}-tls
  namespace: ${NS}
spec:
  secretName: kafka-${i}-tls
  duration: 8760h
  renewBefore: 720h
  commonName: kafka-${i}
  dnsNames:
    - kafka-${i}
    - kafka-${i}.kafka
    - kafka-${i}.kafka.${NS}.svc
    - kafka-${i}.kafka.${NS}.svc.cluster.local
    - kafka-${i}-external.${NS}.svc.cluster.local
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  issuerRef:
    name: kafka-broker-ca
    kind: ClusterIssuer
    group: cert-manager.io
EOF
  echo "Wrote $f"
done

echo ""
echo "Next:"
echo "  1. kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.5/cert-manager.yaml  # or your supported version"
echo "  2. kubectl apply -k ${REPO_ROOT}/infra/k8s/kafka-certs/"
echo "  3. Wire per-broker secrets into Kafka StatefulSet (PEM/JKS) — see infra/k8s/kafka-certs/README.md"
echo "Colima/dev without cert-manager: keep using scripts/kafka-ssl-from-dev-root.sh (shared JKS + full SAN list)."
