#!/usr/bin/env bash
# Emit docs/architecture/services/<label>.md from live Postgres (tables + outbox / processed_events heuristics).
# Usage: ./generate-service-arch-docs.sh [repo_root]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${1:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
DOCS="$REPO_ROOT/docs/architecture/services"

export PGPASSWORD="${PGPASSWORD:-postgres}"
PGHOST="${PGHOST:-127.0.0.1}"
PGUSER="${PGUSER:-postgres}"

if [[ -z "${INSPECT_DBS:-}" ]]; then
  INSPECT_DBS="5441:auth:auth
5442:listings:listings
5443:bookings:bookings
5444:messaging:messaging
5445:notification:notification
5446:trust:trust
5447:analytics:analytics
5448:media:media"
fi
if [[ -f "${INSPECT_DBS:-}" ]]; then
  DB_LIST="$(cat "$INSPECT_DBS")"
else
  DB_LIST="$INSPECT_DBS"
fi

mkdir -p "$DOCS"

while IFS= read -r line; do
  [[ -z "$line" ]] && continue
  port="${line%%:*}"
  rest="${line#*:}"
  dbname="${rest%%:*}"
  label="${rest#*:}"
  label="${label:-$dbname}"
  out_md="$DOCS/${label}.md"

  if ! PGPASSWORD="$PGPASSWORD" psql -h "$PGHOST" -p "$port" -U "$PGUSER" -d "$dbname" -X -t -A -c "SELECT 1" &>/dev/null; then
    echo "skip $label — not reachable"
    continue
  fi

  tmp="$(mktemp)"
  PGPASSWORD="$PGPASSWORD" psql -h "$PGHOST" -p "$port" -U "$PGUSER" -d "$dbname" -X -t -A -F $'\t' -c "
    SELECT table_schema, table_name
    FROM information_schema.tables
    WHERE table_type = 'BASE TABLE'
      AND table_schema NOT IN ('pg_catalog', 'information_schema')
    ORDER BY 1, 2;
  " >"$tmp"

  outbox_lines=()
  proc_lines=()
  other_lines=()
  while IFS=$'\t' read -r sch tbl; do
    [[ -z "${sch:-}" ]] && continue
    full="$sch.$tbl"
    case "$tbl" in
      *outbox*) outbox_lines+=("- \`$full\`") ;;
      *processed_events*) proc_lines+=("- \`$full\`") ;;
      *) other_lines+=("- \`$full\`") ;;
    esac
  done <"$tmp"
  rm -f "$tmp"

  fmt_list() { printf '%s\n' "${@:-}" | sed '/^$/d' | sort -u || true; }

  {
    echo "# ${label} service — data architecture"
    echo ""
    echo "Autogenerated from \`$PGHOST:$port\` database \`$dbname\`. Regenerate with \`make generate-architecture-docs\` (requires reachable Postgres)."
    echo ""
    echo "## Overview"
    echo ""
    echo "The **${label}** bounded context owns this database. Other services reference its aggregates by **stable IDs** (UUIDs), not foreign keys. Cross-context consistency is **eventual**: transactional **outbox** rows and **processed_events** (where present) implement at-least-once Kafka delivery and idempotent consumption."
    echo ""
    echo "## Data ownership"
    echo ""
    echo "### Primary and supporting tables"
    echo ""
    if ((${#other_lines[@]})); then fmt_list "${other_lines[@]}"; else echo "_None listed._"; fi
    echo ""
    echo "### Outbox (event production)"
    echo ""
    if ((${#outbox_lines[@]})); then fmt_list "${outbox_lines[@]}"; else echo "_No table name matched \`*outbox*\`._"; fi
    echo ""
    echo "### Processed events / idempotency (consumption)"
    echo ""
    if ((${#proc_lines[@]})); then fmt_list "${proc_lines[@]}"; else echo "_No \`processed_events\` table detected by name._"; fi
    echo ""
    echo "## Event production"
    echo ""
    echo "When an \`outbox_events\` (or similar) table exists, domain writes and outbox inserts commit in the **same** database transaction. A publisher process reads unpublished rows, emits to Kafka, then marks them published. See \`infra/db/*-outbox.sql\` and \`docs/OUTBOX_PUBLISHER_AND_CONSUMER_CONTRACT.md\` if present."
    echo ""
    echo "## Event consumption"
    echo ""
    echo "Consumers that must be idempotent use \`processed_events\` (or equivalent): insert event id before handling; on conflict skip. See \`infra/db/*-processed-events.sql\` for this repository’s pattern."
    echo ""
    echo "## Write vs projection model"
    echo ""
    echo "**Write model** tables hold authoritative state for this context. **Projection** or **analytics** tables (if any) are derived from events or batch jobs and may lag; they are not sources of truth for cross-service invariants."
    echo ""
    echo "## Cross-service relationships"
    echo ""
    echo "There are **no foreign keys** to other services’ databases. Integration is via **events** and **API calls** using IDs returned at creation time."
    echo ""
    echo "## Failure and consistency"
    echo ""
    echo "Single-DB transactions are **ACID**. Cross-service effects are **eventually consistent** unless you add synchronous API coupling (avoid for autonomy). Outbox ensures publish-after-commit ordering for emitted events."
    echo ""
    echo "## Physical ER diagram"
    echo ""
    echo "See [\`diagrams/physical/${label}.svg\`](../../diagrams/physical/${label}.svg) (and matching \`.png\`) after \`make generate-diagrams\`."
  } >"$out_md"

  echo "  wrote $out_md"
done <<<"$DB_LIST"
